### ISSUE TITLE
CreateTask target

### ISSUE THREAD

**Issue by hazcod** [qzyse2017/openvas-golang-lib#1]
Hi,

How does one create a scanning task? After creating a task, one receives a scan id string.
But the method expects an `openvas.Target`?

```go
	taskId, err = omp.CreateTask(&openvas.Task{
		Text:    target.Text,
		ID:      target.ID,
		Name:    target.ID,
		Comment: target.Name,
		Config:  &config,
		Target:  &openvas.Target{
			Text:         target.Text,
			ID:           target.ID,
			Name:         target.Name,
			Hosts:        []string{target.Hosts},
			ExcludeHosts: nil,
		},
	})
```

**Comment by prism4time** [comment]
Hi
the lib needs to create a target first and you can then pass the target id to the ``openvas.Target`` struct, ``CreateTask`` just uses the id of  the ``Target`` parameter.  You may refer to the unit test here https://github.com/qzyse2017/openvas-golang-lib/blob/master/cmd_task_test.go#L80

Sorry I did not come up with a straightforward way to create a task and pass related parameters.
I have not used the lib much either.  Sincerely looking forward to your suggestions on a better way to use openvas with golang. 

 @hazcod

**Comment by hazcod** [comment]
Hi @qzyse2017 , i'm a bit confused with OMPTarget and Target.
So `Target` should actually receive `OMPTarget.ID` ?

**Comment by prism4time** [comment]
You are right, its OMPTarget.ID, the corresponding original command is what is described here https://docs.greenbone.net/API/OMP/omp.html#command_create_target @hazcod

**Comment by hazcod** [comment]
I see, thanks. Are we required to setup a `Scanner` object?
I'm not quite sure why I would need to create one.

**Comment by prism4time** [comment]
You may use https://github.com/qzyse2017/openvas-golang-lib/blob/master/cmd_scanner.go#L107 `GetDefaultScanner` which corresponds to the default scanner. I remember I did not need to create one myself when I wrote my code 🤔 @hazcod

**Comment by hazcod** [comment]
Hmm, that function isn't available in my package scope for some reason.
Thanks for the support @qzyse2017 !

**Comment by prism4time** [comment]
@hazcod  maybe I need to fix my code, what is the reason? 🤔
